### ISSUE TITLE
Errors in DEV are sent, though DEV is not in notify_release_stage

### ISSUE THREAD

**Issue by ptim** [bugsnag/bugsnag-python#121] opened 2017-07-15 14:12 UTC
This certainly sounds like a configuration issue, but I think I'm doing it correctly:

I have a django app with:

    bugsnag==3.1.0
    Django==1.9.6

With the following config:

    # settings.py
    # https://docs.bugsnag.com/platforms/python/django/#basic-configuration
    BUGSNAG = {
        'api_key': os.getenv('BUGSNAG_API_KEY', ''),
        # don't log in development
        'release_stage': os.getenv('DJANGO_MODE', 'production').lower(),
        'notify_release_stages': ['production', 'staging'],
    }

and the following env settings:

    ./manage.py diffsettings

    # formatted for legibility
    BUGSNAG = {
        'api_key': '-redacted-', 
        'release_stage': 'debugtoolbar', 
        'notify_release_stages': ['production', 'staging']
    }

I'm seeing reports in every release_stage - am I doing something wrong?

**Comment by ptim** [comment] 2017-07-15 14:15
ugh, please excuse the obvious typo in the issue title... the code snippets are correct.. couldn't edit the title :/

**Comment by ptim** [comment] 2017-07-16 06:05
This is still bugging me... 

I've checked out the [example django project](https://github.com/bugsnag/bugsnag-python/blob/master/example/django/README.md), and run it with `Django==1.9` (to match my project), and my notify is silenced in dev as expected if I set:

    BUGSNAG = {
        'api_key': 'redacted',
        'release_stage': os.getenv('DJANGO_MODE', 'dev').lower(),
        'notify_release_stages': ['production', 'staging'],
    }


Back in my project, I added the following:

    # /.direnv/python-3.6.1/lib/python3.6/site-packages/bugsnag/django/__init__.py

    print('[BUGSNAG] release_stage: \'{}\', notify_release_stages: {}\n'.format(
        bugsnag.configuration.get('release_stage'),
        bugsnag.configuration.get('notify_release_stages'),
    ))

Prints: 

> [BUGSNAG] release_stage: 'debugtoolbar', notify_release_stages: ['production', 'staging']

But notify still fires / errors are still logged on Bugsnag...

Is there a problem with my logging configuration?

    # https://docs.djangoproject.com/en/1.9/topics/logging/
    LOGGING = {
        ...
        'handlers': {
            'bugsnag': {
                'level': 'INFO',
                'class': 'bugsnag.handlers.BugsnagHandler',
            },
        },
        ...
        'loggers': {
            '': {
                'handlers': ['console', 'file', 'bugsnag'],
                'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
                'propagate': True,
            },
            ...
        },
    }

Originally I had the `root` key set, per your docs, but that was nixing my existing config...

>In case you were curious, 'root' overrides '' if you define both, just because the root entry is processed last.
>https://stackoverflow.com/a/24146729/2586761

**Comment by Cawllec** [comment] 2017-08-16 14:47
I've been unable to replicate your bug so far, your configuration seems to be working perfectly well in testing.  
Is there any more configuration you'd be willing to share to track down the cause of this problem?

**Comment by ptim** [comment] 2017-08-16 23:47
Thanks for the reply @Cawllec - I'm not on this job at the moment... last I recall, I inserted a breakpoint in here:

```
File: .direnv/python-3.6.1/lib/python3.6/site-packages/bugsnag/client.py
133:     def should_deliver(self, notification):
134:         # Return early if we shouldn't notify for current release stage
135:         if not self.configuration.should_notify():
136:             return False
137: 
138:         # bugsnag shouldn't be firing in dev
139:         import wdb; wdb.set_trace()
140: 
141:         # Return early if we should ignore exceptions of this type
142:         if self.configuration.should_ignore(notification.exception):
143:             return False
144: 
145:         return True
146: 
```

I think part of the issue is that if I save a syntax error (eg broken import or similar) then django settings are not available, so the `should_notify` doesn't yet have the correct configuration..

Just guesses really, python is not my main thing :/

Thanks

**Comment by Cawllec** [comment] 2017-09-01 13:12
Closing this as unable to reproduce

**Closed by Cawllec** 2017-09-01 13:12 UTC

**Comment by kylef** [comment] 2017-09-01 17:26
@ptim If you have any errors or logged `info` or higher events that are logged BEFORE the `BugsnagMiddleware` is instantiated then they will indeed be logged with the default settings. Since `BUGSNAG_API_KEY` is set, then by default Bugsnag client will have an API key and the notification will be successful.

I think there are two work arounds you can do:

1) Make your logging stricter so the events that are triggered are not logged.
2) Perhaps import bugsnag and configure `notify_release_stages` at an earlier stage. This could be achieved by adding the following to your Django `settings.py`:

    ```python
    import bugsnag
    bugsnag.configure(notify_release_stages=['x'])
    ```

**Comment by ptim** [comment] 2017-09-05 00:21
This is great, thanks @kylef ... I found that I also had to set `auto_notify` to false in to prevent logging.
