### ISSUE TITLE
HTTPSConnectionPool, Max retries exceeded, Caused by SSLError, EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by rserro** [bugsnag/bugsnag-python#292] opened 2021-06-27 01:26 UTC
I have looked at https://github.com/bugsnag/bugsnag-python/issues/157 but could still not solve the problem.

### Describe the bug
I am unable to get rid of the error below happening when running Django on AWS Lambda using Serverless.com.

### Steps to reproduce
I am unable to reproduce the error so I am appending the detailed log:

requests.exceptions.SSLError
/var/task/requests/adapters.py:514
HTTPSConnectionPool(host='notify.bugsnag.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Jun 27th, 2021, 01:08:01 UTC

STACKTRACE

Traceback (most recent call last):
  File "/var/lang/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                  self.run()
  File "/var/lang/lib/python3.8/threading.py", line 870, in run
                  self._target(*self._args, **self._kwargs)
  File "/var/task/requests/api.py", line 119, in post
      return request('post', url, data=data, json=json, **kwargs)
  File "/var/task/requests/api.py", line 61, in request
          return session.request(method=method, url=url, **kwargs)
  File "/var/task/requests/sessions.py", line 542, in request
          resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 655, in send
          r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 514, in send
                  raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='notify.bugsnag.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### Environment
Django 3.2.3
Python 3.8.10
Bugsnag 4.0.3
Serverless 2.47.0

### Other
[packages]
boto3 = "==1.17.73"
bugsnag = "==4.0.3"
cryptography = "==3.4.7"
django = "==3.2.3"
django-cors-headers = "==3.7.0"
django-filter = "==2.4.0"
django-storages = "==1.11.1"
djangorestframework = "==3.12.4"
firebase-admin = "==5.0.0"
pillow = "==8.2.0"
pyjwt = "==2.1.0"
pymysql = "==1.0.2"
python-decouple = "==3.4"
unidecode = "==1.2.0"
werkzeug = "==1.0.1"

[dev-packages]
coverage = "==5.5"
fabric3 = "==1.14.post1"
flake8 = "==3.9.2"
gunicorn = "==20.1.0"
isort = "==5.8.0"
memcache = "==0.5.1"
pytest = "==6.2.4"
pytest-cov = "==2.12.0"
pytest-django = "==4.3.0"
redis = "==3.5.3"

**Comment by yousif-bugsnag** [comment] 2021-06-28 09:35
Hi @rserro,

Bugsnag doesn't yet officially support AWS Lambda for Python, however it's on our product roadmap and something we are planning to add support for in future (see #89). 

However it should be possible to make it work on some AWS Lambda platforms by configuring Bugsnag to send events synchronously to ensure the errors are sent before the process terminates: https://docs.bugsnag.com/platforms/python/other/configuration-options/#asynchronous

**Comment by yousif-bugsnag** [comment] 2021-06-28 09:36
Closed as duplicate of #89

**Closed by yousif-bugsnag** 2021-06-28 09:36 UTC
Labels: duplicate

**Comment by dacevedo12** [comment] 2022-03-28 14:06
I'm having a similar error running on AWS EC2

`requests.exceptions.SSLError: HTTPSConnectionPool(host='sessions.bugsnag.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))`

Should I open a new issue or is it better to repoen this one? @yousif-bugsnag

**Comment by johnkiely1** [comment] 2022-03-30 08:22
Hi @dacevedo12. 

Yes this sounds like a different issue, especially if you are not using AWS Lambda, I would suggest you open a new GH issue or contact us via support@bugsnag.com. If you could share as much detail around your configuration and infrastructure setup as possible that would be helpful.
