### ISSUE TITLE
Exception in before_notify callback triggers an infinite notification loop

### ISSUE THREAD

**Issue by peplin** [bugsnag/bugsnag-python#60] opened 2015-05-02 22:59 UTC
It can probably be argued that this is a bug in my code, and not the Bugsnag notifier's responsibility, but I thought I would bring this to your attention in case there is an easy fix.

If your registered callback triggers an exception, you can get into an infinite loop starting from https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/middleware.py#L120

**Comment by peplin** [comment] 2015-05-02 23:06
My mistake, I'm misinterpreting the error - I'll re-open something with more details if I can track it down.

**Comment by peplin** [comment] 2015-05-02 23:40
I'm re-opening this because I was able to narrow down the issue and understand it better.

We have a `before_notify` handler registered with the Bugsnag notifying in our app. For a reason unrelated to Bugsnag, it was raising an exception. I think this is the order of events:

1. An exception occurs in the app. Bugsnag catches it and starts to build the notification.
1. The `before_notify` handler is called, and that raises its own exception.
1. We get the `exception in middleware` error, then go to [this line](https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/middleware.py#L120) to finish notifying about the exception anyway.
1. The `before_notify` handler is called again, raising another exception

This continues until the max stack depth is exhausted. 

Besides never raising exceptions in the `before_notify` callback, anything we can do to avoid this? Thanks!

**Comment by keeganlow** [comment] 2015-05-21 00:39
Hey @peplin, sorry for the delay in getting to this.

I just did some testing with having a `before_notify` callback raise an exception. I wasn't able to recreate the notification loop you're seeing. Can you provide a minimal example that recreates this behavior?

Thanks!

**Comment by ksookocheff-va** [comment] 2015-06-15 21:00
We had a similar issue. Note that the bugsnag configuration is a singleton and you cannot add a `before_notify` callback every request. You need to add this once on app initialization only.

**Comment by kattrali** [comment] 2016-01-15 16:59
I've been unable to reproduce this, so I'm closing it for now. We can reopen at a later time if we can get a gist of an example to replicate this behavior.

**Closed by kattrali** 2016-01-15 16:59 UTC

**Comment by steve-nester-uk** [comment] 2020-07-23 06:59
Thanks for raising @rcjsuen, can you advise if, like the OP's case, your `before_notify` was raising an exception?
Would you be able to provide the steps to replicate and example code?

**Comment by rcjsuen** [comment] 2020-07-23 11:30
> 
> 
> Thanks for raising @rcjsuen, can you advise if, like the OP's case, your `before_notify` was raising an exception?

Not sure given. I don't see `before_notify` anywhere in the stack trace so maybe not?

> Would you be able to provide the steps to replicate and example code?

Well, I can tell you that it's a Flask `POST` triggered by pushing an HTML form's button. The Celery task that gets triggered with `task.apply(*)` is throwing an exception.

**Comment by steve-nester-uk** [comment] 2020-07-23 13:22
Thanks @rcjsuen we can't see evidence that the Bugsnag SDK is causing your error, but if you find evidence that's it's caused by the notifier, please share a reproduction example and we'll review.
